name: Dfy
description: A new Flutter project.

# The following line prevents the package form being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Dart
  dartx: ^0.7.1
  flutter_html: ^2.1.1
  auto_size_text: ^3.0.0-nullsafety.0
  optimized_cached_image: ^3.0.0
  clipboard: ^0.1.3
  list_tile_switch: ^1.0.0
  #Favourite library
  share: ^2.0.1
  provider: ^5.0.0
  device_info: ^2.0.0
  flutter_bloc: ^7.0.0
  package_info: ^2.0.0
  google_fonts: ^2.0.0
  connectivity: ^3.0.3
  url_launcher: ^6.0.5
  path_provider: ^2.0.1
  webview_flutter: ^2.0.10
  shared_preferences: ^2.0.5
  font_awesome_flutter: ^9.0.0
  lint: ^1.6.0
  table_calendar: ^3.0.2
  image_picker: ^0.8.4+3

  #Library helpful
  intl: ^0.17.0
  event_bus: ^2.0.0
  equatable: ^2.0.0
  fluttertoast: ^8.0.3
  retrofit: ^2.0.1
  json_annotation: ^4.0.1
  flutter_screenutil: ^5.0.0
  cached_network_image: ^3.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0
  logger: any
  rxdart: ^0.27.1
  expandable: 5.0.1
  sliding_up_panel: ^2.0.0+1

  carousel_slider: ^4.0.0-nullsafety.0
  dots_indicator: ^2.0.0
  #svg
  flutter_svg: ^0.22.0
  formz: ^0.4.1

  # The following adds the Cupertino Icons fonts to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dart_ipify: ^1.1.0
  crypto: ^3.0.1
  #  vibration: ^1.7.3
  #  flutter_slidable: ^0.6.0

  shimmer: ^2.0.0

  # GETX
  get: ^4.1.4
  pretty_dio_logger: ^1.1.1

  injectable: ^1.4.1
  freezed: ^0.14.2
  #  get_storage: ^2.0.2
  # Loading style
  tuple: ^2.0.0
  #flutter_appavailability: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner:  #flutter pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^4.1.0
  injectable_generator: ^1.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons fonts is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
flutter_intl:
  enabled: true